[workspace]
members = [
  "crates/sidecar-runner",
  "crates/kicad-sidecar",
  "crates/freecad-sidecar",
]
resolver = "2"

[workspace.package]
edition = "2021"
license = "Apache-2.0"
version = "0.1.0"

[workspace.dependencies]
serde = { version = "1", features = ["derive"] }
serde_json = "1"
thiserror = "1"
hnf-core = { path = "../../hnf/crates/hnf-core" }
hnf-kicad = { path = "../crates/hnf-kicad" }
hnf-freecad = { path = "../crates/hnf-freecad" }
sidecar-protocol = { path = "../crates/protocol" }
